PGUSER added to not connect to db as root

diff --git a/script/enterprise-migrations b/script/enterprise-migrations
--- a/script/enterprise-migrations
+++ b/script/enterprise-migrations
@@ -19,6 +19,11 @@ main() {
     exit 1
   }
 
+  [[ "${PGUSER}" ]] || {
+    echo "Missing \$PGUSER"
+    exit 1
+  }
+
   [[ "${DATABASE_URL}" ]] || {
     echo "Missing \$DATABASE_URL"
     exit 1
@@ -40,7 +45,7 @@ main() {
 }
 
 __pgdb_exists() {
-  psql -ltA | if grep -qE "^${PGDATABASE}\|"; then
+  psql -ltA -U ${PGUSER} | if grep -qE "^${PGDATABASE}\|"; then
     return 0
   else
     return 1
